credentials:
  usernames:
    johndoe:
      name: John Doe
      password: abc123  # Use plain-text (auto hashes) or hash it if you prefer
      email: johndoe@example.com

cookie:
  name: some_cookie_name
  key: some_signature_key
  expiry_days: 30
